### ISSUE TITLE
error display with Chinese words

### ISSUE THREAD

**Issue by shuxiao9058** [thisch/gerrit.el#47]
<img width="1119" alt="image" src="https://github.com/thisch/gerrit.el/assets/3312525/cd33551e-dee4-471c-8b63-922a813addc3">

**Comment by thisch** [comment]
Hi! Thx for creating this report. I guess you have tried the `gerrit-rest-change-patch` function, right?

**Comment by thisch** [comment]
Friendly ping @shuxiao9058
